<?php

return [

    'title' => 'Data Pool' ,
    'sub-title' => 'Interested in traffic data but don\'t want to roll out your own devices?<br><br>
Welcome to Telraam\'s Data Pool - the ultimate destination for unlocking the power of community-sourced
                    mobility data. Dive into a wealth of real-time information, generated by our network of citizen-operated devices,
                    and revolutionize your approach to urban planning, research, and development.',

    // section 1 with 3 columns
    'section-1-title' => 'Unlocking Urban Mobility Insights with Telraam\'s Data Pool',

    'section-1-what-title' => 'What is the Data Pool?',
    'section-1-what-text'     => 'Telraam\'s Data Pool is a user-friendly module within the Network subscription that lets you access data from existing devices outside your fleet. By using this pool, urban planners, researchers, and government organisations can get unprecedented insights to shape the future of our cities.',

    'section-1-key-title' => 'Key Features',
    'section-1-key-title-1'  => 'Real-Time Updates',
    'section-1-key-text-1'   => 'Stay informed with continuously updated data streams, providing the latest information on urban mobility dynamics.',
    'section-1-key-title-2'  => ' Advanced API',
    'section-1-key-text-2'   => 'With the data pool you can access advanced API analytics with custom data limits, 15-minute resolution, 10 modes, typical data, and more.',
    'section-1-key-title-3'  => 'No maintenance or service requirements',
    'section-1-key-text-3'   => 'Gain detailed insights without ownership responsibilities or the need for installations or support.',

    'section-1-benefit-title' => 'Who Can Benefit?',
    'section-1-benefit-text'     => 'Telraam\'s Data Pool is designed to serve a wide range of clients, including:
                <ul class="jump-in">
                    <li><strong>Urban Planners:</strong> Shape strategic transportation plans, refine traffic
                        management strategies, and improve infrastructure development.</li>
                    <li><strong>Researchers & Campaigners:</strong> Conduct in-depth studies on mobility trends, environmental
                        impacts, and social dynamics within urban environments.</li>
                    <li><strong>City Governments:</strong> Support evidence-based policy making, improve public
                        transportation systems, and address urban challenges effectively</li>
                </ul>',

    // section 2
    'section-2-title' => 'Our external advisory council',
    'section-2-text'  => 'At Telraam, we recognize the importance of ensuring that mobility data collected from our citizen-operated devices is used in a
     socially-responsible manner.<br>
<br>
That\'s why we\'ve set up an external advisory council, representing the communities we serve. This council ensures that crowdsourced data meets ethical
standards, respects individual privacy, and benefits society. By involving citizens, we aim for transparency, accountability, and fairness in all our
data-driven initiatives.<br>
<br>
We organise around 5 digital sessions per year to gather input, which will be openly published on our website. If you’d like to participate,
please <a href="/en/contact-us">get in touch</a>.',

    // section 3
    'section-3-title' => 'How does it work?',
    'section-3-text'  => '<ol>
<li>In your Network dashboard, browse the map and add segments to the "basket"</li>
<li>Decide if you\'re interested in one-time historical data or a subscription to get ongoing live data</li>
<li>Confirm the segment choices</li>
<li>Make sure you have sufficient credits.</li>
</ol>',


    // section 4
    'section-4-title' => 'Beta',
    'section-4-text'  => 'Currently the data pool is in beta only. 
    <br>
    However if you want access do not hesitate to <a href="/en/contact-us">apply for a partnership</a>!<br><br>',



];
