<?php

return [

    'title'           => 'Preguntas frecuentes',

    'question-1'           => '¿Puedo entregar mi Telraam V1 y actualizar a un dispositivo Telraam S2 a un precio reducido?',
	'answer-1'           => 'No; debido al avance tecnológico que supone el dispositivo Telraam S2 respecto al sensor Telraam V1, no es posible ofrecer una reducción de precio basada en la entrega del dispositivo anterior para nuevas compras de Telraam S2 a los propietarios de Telraam V1. No obstante, si dispone de un Telraam V1, siempre puede vender los componentes de su dispositivo (ordenador Raspberry Pi 3A+ y módulo de cámara Raspberry Pi) en el mercado de electrónica para aficionados para contribuir al coste de un nuevo Telraam S2, o puede convencer a su administración local para que ponga en marcha un nuevo proyecto Telraam financiado y, posiblemente, obtener así un nuevo dispositivo Telraam S2. Mientras tanto, todos los dispositivos Telraam V1 seguirán funcionando y podrá ver los datos de su dispositivo Telraam V1 en la red Telraam también en el futuro. Sin embargo, no se realizarán más actualizaciones de funciones para los dispositivos Telraam V1.',
 	 	'question-2'           => '¿Qué tipo de datos envía un dispositivo Telraam S2?',
 	'answer-2' 			=> 'La privacidad siempre es una prioridad máxima para nosotros en Telraam. El reconocimiento de imágenes basado en IA y el seguimiento de objetos se limita estrictamente a los dispositivos de borde (es decir, ocurre en el propio dispositivo), y solo los datos de recuento agregado (y de velocidad) resultantes se envían al servidor de Telraam cada 15 minutos. Dado que los datos son agregados, no se transmiten los parámetros individuales de cada objeto.',
 	 	'question-3'           => '¿Qué tipo de conexión de red necesita el Telraam S2 para enviar datos?',
 	'answer-3' 			=> 'Nuestros dispositivos Telraam S2 incluyen una tarjeta SIM Thingstream integrada que proporciona conexión de datos móviles de bajo consumo mediante la banda de frecuencia LTE-M o NB-IoT del proveedor o los proveedores de red celular local. Aunque estas tecnologías están disponibles casi en todo el mundo, consulte el <a href="https://www.u-blox.com/en/iot-network-coverage" target="_blank">mapa de cobertura de red</a> antes de adquirir un dispositivo Telraam S2 para asegurarse de que su nuevo sensor podrá enviar datos a los servidores de Telraam. El Telraam S2 no necesita conexión wifi, y no existe la posibilidad de utilizar wifi en lugar del enlace de datos móviles proporcionado.',
 	 	'question-4'           => '¿Qué tipos de usuarios de la vía puede detectar el Telraam S2?',
 	'answer-4' 			=> 'El nuevo chip de IA del Telraam S2 puede distinguir entre diez modos de tráfico: peatones, cochecitos de bebé, bicicletas, motocicletas, coches, camiones ligeros, remolques, camiones y autobuses. Por el momento, los datos de tráfico procedentes de los dispositivos Telraam S2 se visualizan de la misma manera que siempre se han visualizado los datos de los dispositivos Telraam V1: los recuentos se agregan en las cuatro categorías de peatones, vehículos de dos ruedas, coches y vehículos pesados. En segundo plano, los datos ya se guardan para cada uno de los diez modos en los dispositivos Telraam S2, y la interfaz web y la API de tráfico se actualizarán próximamente para incluir todos los nuevos modos.',
 	 	'question-5'           => '¿Cuál es la exactitud y precisión del Telraam S2?',
 	'answer-5' 			=> 'La exactitud y precisión del Telraam S2 se valida y documenta de forma continua. Nuestra documentación abarca la <a href="https://github.com/Telraam/Telraam-S2/blob/main/count-performance-validation.md" target="_blank">exactitud del recuento</a>, la <a href="https://github.com/Telraam/Telraam-S2/blob/main/count-consistency-validation.md" target="_blank">precisión del recuento</a> y las <a href="https://faq.telraam.net/article/41/speed-measurements-with-telraam-s2" target="_blank">mediciones de velocidad</a>. En general, la exactitud diurna actual es típicamente del 90-95 % para una gran muestra de ubicaciones de prueba, con los peatones como única categoría con un rendimiento notablemente inferior en algunas circunstancias específicas. La precisión no es un factor limitante, ya que la dispersión entre dispositivos es baja. Para un rendimiento óptimo, asegúrese de que su Telraam S2 está instalado en una ubicación adecuada (véase Dónde puedo instalar un Telraam S2) y configure una <a href="https://faq.telraam.net/article/66/region-of-interest-roi-and-roi-selection-with-telraam-s2" target="_blank">región de interés</a> durante el registro.',
 		 	'question-7'           => '¿Dónde puedo instalar un Telraam S2?',
 	'answer-7' 			=> 'Los dispositivos Telraam S2 deben instalarse
<ul class="jump-in">
<li>en una ventana que ofrezca una vista clara y sin obstáculos de toda la anchura de la calle situada debajo (sin árboles grandes, postes o barandillas anchas, ni mobiliario urbano extenso en el campo de visión)</li>
<li>junto a una carretera que discurra paralela a la ventana, sin intersecciones (esquinas, curvas) a la vista</li>
<li>no en la planta baja, de modo que el dispositivo pueda observar el tráfico en un ángulo ligeramente descendente (el primer piso — o segundo piso según la terminología americana — será óptimo en la mayoría de los casos, mientras que los pisos superiores podrían funcionar en calles muy anchas con varios carriles, de modo que el tráfico se vea en un ángulo de 30-45 grados).</li>
</ul>
<br>
Algunos ejemplos de ubicaciones buenas y malas se muestran en nuestro artículo de FAQ <a href="https://faq.telraam.net/article/3/requirements-for-the-installation-of-a-telraam-in-my-window"  target="_blank">Requisitos para la instalación de Telraam en mi ventana</a>.',

 	 	'question-8'           => '¿Puedo apagar la pantalla LCD de mi dispositivo Telraam S2?',
 	'answer-8' 			=> '¡Sí! Simplemente pulse el botón hasta que la pantalla se apague. No se preocupe, el dispositivo seguirá contando con la pantalla apagada. Puede reactivar la pantalla pulsando el botón de nuevo.',
 	 	'question-9'           => 'Mi Telraam S2 parece pasar por alto algo de tráfico. ¿Qué puedo hacer?',
 	'answer-9' 			=> 'En primer lugar, asegúrese de que su Telraam está instalado correctamente y ajuste su región de interés si no lo hizo durante la instalación. Si ya lo ha hecho, compruebe que la región de interés seleccionada cubre realmente toda la anchura de la carretera. Incluso con la mejor configuración, a menudo no es posible que el dispositivo vea a los peatones que caminan justo debajo de la ventana, de modo que no espere que dichos usuarios sean contabilizados por el Telraam S2. Si un área de la carretera no es visible en la imagen de la región de interés, los usuarios de la vía que pasen por allí no serán contados. Del mismo modo, si la acera del otro lado de la calle está parcialmente cubierta por una fila de árboles o coches aparcados, es probable que su Telraam tenga dificultades para contar a cada peatón que pase parcialmente oculto. Los grupos de peatones y ciclistas muy densos y numerosos también resultarán muy difíciles de contar con precisión, simplemente debido a las limitaciones tecnológicas de un dispositivo tan pequeño. Si cree que su Telraam debería contar con mayor precisión incluso después de considerar todos los factores mencionados, siempre puede grabar un vídeo estable (sin sostenerlo con la mano), de alta resolución (mínimo 1080p) y gran angular (de modo que toda la superficie de la calle sea visible) con su smartphone o una cámara GoPro que contenga 15 minutos de tráfico desde la ventana donde está instalado su Telraam S2 y enviárnoslo. Podemos utilizar este vídeo para comprender por qué su dispositivo tiene un rendimiento inferior al esperado, y podría servirnos para mejorar nuestro algoritmo de detección en el futuro.',

 	'text-final' 			=>'Si aún tiene preguntas específicas, no dude en escribirnos a <a href="mailto:support@telraam.net"  target="_blank">support@telraam.net</a>',

    'disclaimer' => 'El dispositivo incluye una tarjeta SIM y una suscripción de datos que se conecta a la red móvil LTE-m o NB-iot. En algunos países esta tecnología de comunicación aún no está disponible. Si no está seguro/a, póngase en contacto con su proveedor local.<br>
<br>
El dispositivo cuenta con la aprobación CE así como con una <a href="/downloads/FCC-certificate.pdf" target="_blank">aprobación FCC</a>.<br>
<br>
El dispositivo incluye un pequeño soporte para montar en la ventana. Los residuos de pegamento son eliminables.<br>',



];
